#!/bin/bash
BUILD=$(curl "https://www.random.org/integers/?num=1&min=1&max=65535&col=1&base=10&format=plain&rnd=new")
echo "numero ->" $BUILD
docker build  -f $DOCKERFILE_PATH -t $IMAGE_NAME-$BUILD --build-arg version=1.0.0.$BUILD .
docker push $IMAGE_NAME-$VERSION
